memory_limit = 1024M
upload_max_filesize = 100M
post_max_size = 110M
max_execution_time = 300
max_input_time = 300
date.timezone = Asia/Kuala_Lumpur
expose_php = Off
opcache.enable = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
